><h1>**Geo-bibliometrics**</h1>
<h3>Integration of bibliographic openly accessible databases and location-, feature, and geographic-based search and discovery of scientific literature</h3>
<h3><font color = "Grey">Jacobs University Fall 2017 Final Presentation</h3>
<h2><font color = "Grey">Jaeho Shin</h2>

><h3> Objective: Mars Polygon Mapping and Visualization of Bibliographic Data </h3>

><h1> My Tasks </h1>
><h2><font color = "Grey">1. Data Creation</h2>
><h2><font color = "Grey">2. Visualization</h2>
><h2><font color = "Grey">3. Analysis</h2>

><h1>1. Data Creation 1/3 </h1>
<h3><font color = "Grey">Mars Gazetteer Data + Polygon Data </h3>

In [35]:
from IPython.display import HTML
HTML('<iframe width="800" height="600" src="https://planetarynames.wr.usgs.gov/Feature/5931;jsessionid=B3FF5112EDAF5866E6836D2C05E63DD3" frameborder="0" allowfullscreen></iframe>')

In [19]:
# Extract Polygon Data from https://planetarynames.wr.usgs.gov/Feature/

class polygon_extract:
    def __init__(self, id):
        self.name = id
        self.urlIAU = "https://planetarynames.wr.usgs.gov/Feature/"
        self.url = self.urlIAU + self.name
        print("url to call: " + self.url)
    
    def extract(self):
        self.r = requests.get(self.url)
        self.data = self.r.text
        self.soup = BeautifulSoup(self.data, "lxml")
        self.feature_panel = self.soup.findAll('table', {'class': 'feature_detail'})
        
        for feature in self.feature_panel:
            try:
                self.name = feature.find('h2').text
            except AttributeError:
                continue
        self.list1 = self.soup.body.findAll(text = re.compile('MULTIPOLYGON'))        
        self.str1 = ''.join(self.list1)
        self.splitList = self.str1.split('\n')
        for item in self.splitList:
            if item.find("MULTIPOLYGON") != -1:
                self.geomStr = item.split('\'')[1]
                self.geomOGR = ogr.CreateGeometryFromWkt(self.geomStr)
                self.coords = json.loads(self.geomOGR.ExportToJson())['coordinates'][0]
                for i in self.coords:
                    for j in i:
                        if j[0] > 180 or j[0] < -180:
                            j[0] = j[0]-360
                        else:
                            pass
                return self.coords
    
            else:
                pass
        return []

In [15]:
import pandas as pd
data_frame = pd.read_csv('mars_gaz.csv', index_col = False)
data_frame

,Feature_ID,Feature_Name,Clean_Feature_Name,Target,Diameter,Center_Latitude,Center_Longitude,Northern_Latitude,Southern_Latitude,Eastern_Longitude,...,Continent,Ethnicity,Feature_Type,Feature_Type_Code,Quad,Approval_Status,Approval_Date,Reference,Origin,polygon
0,4,Abalos Colles,Abalos Colles,Mars,235.83,76.83,-71.65,78.78,74.81,-66.61,...,Europe,Roman,"Collis, colles",CO,mc01,Approved,2003,57.0,"Named for classical albedo feature at 72N, 70W.","[[[-68.42836570739746, 74.97826194763184], [-6..."
1,14147,Abalos Mensa,Abalos Mensa,Mars,129.18,81.17,-75.60,82.40,80.21,-69.48,...,Europe,Roman,"Mensa, mensae",MN,mc01,Approved,2006,57.0,Classical albedo feature name.,"[[[-73.63830757141113, 80.26974678039551], [-7..."
2,14148,Abalos Scopuli,Abalos Scopuli,Mars,109.16,80.72,-76.56,81.96,80.20,-69.48,...,Europe,Roman,"Scopulus, scopuli",SC,mc01,Approved,2006,57.0,Classical albedo feature name.,"[[[-74.60061454772949, 80.95564079284668], [-7..."
3,5,Abalos Undae,Abalos Undae,Mars,442.74,78.52,-87.50,82.20,74.94,-76.97,...,Europe,Roman,"Unda, undae",UN,mc01,Approved,1988,57.0,"Classical albedo feature at 72N, 70W.","[[[-80.35336875915527, 80.58683967590332], [-7..."
4,6,Aban,Aban,Mars,4.28,15.91,111.10,15.94,15.87,111.14,...,Europe,Russia,"Crater, craters",AA,mc14,Approved,1988,36.0,Town in Russia.,"[[[111.101976394653, 15.8708324432373], [111.1..."
5,25,Abus Vallis,Abus Vallis,Mars,60.99,-5.49,-147.20,-5.02,-5.99,-147.16,...,Europe,Great Britain,"Vallis, valles",VA,mc16,Approved,1985,56.0,Classical name for Humber River in England.,[]
6,31,Achar,Achar,Mars,5.36,45.43,123.16,45.48,45.39,123.23,...,South and Central America,Uruguay,"Crater, craters",AA,mc07,Approved,1979,36.0,Town in Uruguay.,"[[[123.165567398071, 45.3864192962646], [123.1..."
7,34,Acheron Catena,Acheron Catena,Mars,421.77,37.47,-100.80,40.70,33.51,-98.29,...,Europe,Greek,"Catena, catenae",CA,mc03,Approved,1979,57.0,"Named for classical albedo feature at 35N, 140W.",[]
8,35,Acheron Fossae,Acheron Fossae,Mars,703.11,38.27,-135.02,40.03,31.47,-129.08,...,Europe,Greek,"Fossa, fossae",FO,mc02,Approved,1979,57.0,"From classical albedo feature at 35N, 140W.","[[[-129.68730354309082, 37.86834907531738], [-..."
9,36,Acidalia Colles,Acidalia Colles,Mars,356.30,50.34,-23.09,52.96,48.42,-19.63,...,Europe,Greek,"Collis, colles",CO,mc04,Approved,2000,71.0,From classical albedo feature name.,"[[[-19.97706413269043, 51.070783615112305], [-..."
10,37,Acidalia Mensa,Acidalia Mensa,Mars,226.86,46.69,-25.34,48.69,45.03,-22.97,...,Europe,Greek,"Mensa, mensae",MN,mc04,Approved,2000,71.0,From classical albedo feature name.,"[[[-23.437543869018555, 47.826555252075195], [..."
11,38,Acidalia Planitia,Acidalia Planitia,Mars,3362.97,49.76,-20.74,68.67,14.76,15.00,...,Europe,Greek,"Planitia, planitiae",PL,mc04,Approved,1973,57.0,"From classical albedo feature at 44N, 21W.","[[[1.239706039428711, 39.644025802612305], [0...."
12,14182,Ada,Ada,Mars,2.09,-3.06,-3.22,-3.04,-3.08,-3.21,...,North America,United States,"Crater, craters",AA,mc19,Approved,"Sep 14, 2006",74.0,"Town in Oklahoma, USA.","[[[-3.2239589691159836, -3.07810401916504], [-..."
13,45,Adamas Labyrinthus,Adamas Labyrinthus,Mars,853.00,35.70,105.12,41.07,30.34,111.46,...,Europe,Greek,"Labyrinthus, labyrinthi",LB,mc06,Approved,1982,57.0,"Classical albedo feature name; ""A River of Dia...","[[[105.58868598937988, 38.07891273498535], [10..."
14,46,Adams,Adams,Mars,90.22,30.91,163.10,31.68,30.15,163.99,...,North America,American,"Crater, craters",AA,mc07,Approved,1973,68.0,Walter S.; American astronomer (1876-1956).,"[[[163.118543624878, 30.1533336639404], [163.1..."
15,65,Aeolis,Aeolis,Mars,0.00,-4.94,145.00,-4.94,-4.94,145.00,...,Europe,Greek,Albedo Feature,AL,mc23,Approved,1958,60.0,Floating island where winds were kept in a cave.,[]
16,15019,Aeolis Dorsa,Aeolis Dorsa,Mars,459.17,-5.05,152.63,-1.03,-8.13,156.42,...,Europe,Greek,"Dorsum, dorsa",DO,mc23,Approved,"Jul 27, 2012",71.0,Classical albedo feature name.,[]
17,66,Aeolis Mensae,Aeolis Mensae,Mars,785.09,-3.25,140.63,2.07,-6.56,146.95,...,Europe,Greek,"Mensa, mensae",MN,mc23,Approved,1976,57.0,Classical albedo feature name.,"[[[140.39999961853027, -0.733449935913086], [1..."
18,15000,Aeolis Mons,Aeolis Mons,Mars,88.99,-5.08,137.85,-4.46,-5.61,138.62,...,Europe,Greek,"Mons, montes",MO,mc23,Approved,"May 16, 2012",71.0,Classical albedo feature name.,[]
19,15001,Aeolis Palus,Aeolis Palus,Mars,111.63,-4.47,137.42,-4.18,-5.39,138.65,...,Europe,Greek,"Palus, paludes",PA,mc23,Approved,"May 16, 2012",71.0,Classical albedo feature name.,[]
20,14165,Aeolis Planum,Aeolis Planum,Mars,852.81,-1.14,144.76,4.40,-6.68,149.98,...,Europe,Greek,"Planum, plana",PM,mc23,Approved,2006,71.0,Classical albedo feature name.,"[[[145.30062675476074, 1.135274887084961], [14..."
21,15031,Aeolis Serpens,Aeolis Serpens,Mars,538.55,-1.38,149.57,2.48,-4.90,152.00,...,Europe,Greek,"Serpens, serpentes",SE,mc23,Approved,"Aug 27, 2012",57.0,Classical albedo feature name.,[]
22,68,Aeria,Aeria,Mars,0.00,9.88,50.00,9.88,9.88,50.00,...,Europe,Greek,Albedo Feature,AL,mc13,Approved,1958,60.0,"Greek name for Egypt; ""far land of mist"".",[]
23,69,Aesacus Dorsum,Aesacus Dorsum,Mars,276.69,36.82,153.15,38.69,34.70,154.72,...,Europe,Greek,"Dorsum, dorsa",DO,mc07,Approved,1985,57.0,"From albedo feature at 45N, 205W.",[]
24,71,Aetheria,Aetheria,Mars,0.00,39.67,130.00,39.67,39.67,130.00,...,Europe,Greek,Albedo Feature,AL,mc07,Approved,1958,60.0,Upper world; land of living.,[]
25,72,Aethiopis,Aethiopis,Mars,0.00,9.88,130.00,9.88,9.88,130.00,...,Europe,Greek,Albedo Feature,AL,mc14,Approved,1958,60.0,Countries of the Ethiopians on southern edge o...,[]
26,79,Aganippe Fossa,Aganippe Fossa,Mars,537.16,-8.49,-126.00,-4.06,-12.85,-124.77,...,Europe,Greek,"Fossa, fossae",FO,mc17,Approved,1976,57.0,Classical albedo feature name.,[]
27,81,Agassiz,Agassiz,Mars,108.77,-69.88,-88.89,-68.97,-70.80,-86.20,...,North America,American,"Crater, craters",AA,mc30,Approved,1973,68.0,Jean L.; American naturalist (1807-1873).,"[[[-88.81912803649902, -70.80104637146], [-88...."
28,114,Airy,Airy,Mars,43.05,-5.14,0.05,-4.77,-5.50,0.42,...,Europe,Great Britain,"Crater, craters",AA,mc20,Approved,1973,68.0,George B.; British astronomer (1801-1892).,"[[[0.064416042621541, -5.500483014882271], [0...."
29,115,Airy-0,Airy 0,Mars,0.79,-5.07,0.00,-5.07,-5.08,0.01,...,Europe,Great Britain,"Crater, craters",AA,mc20,Approved,2003,309.0,Small crater within crater Airy that defines z...,"[[[0.001520156860352, -5.080926895141602], [0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1866,6640,Yar,Yar,Mars,6.18,22.27,-39.15,22.32,22.22,-39.09,...,Europe,Russia,"Crater, craters",AA,mc11,Approved,1976,36.0,Town in Russia.,"[[[-39.147054672240984, 22.2179393768311], [-3..."
1867,14625,Yaren,Yaren,Mars,9.19,-43.88,-137.45,-43.80,-43.96,-137.34,...,Oceania,Nauru,"Crater, craters",AA,mc24,Approved,"Nov 25, 2009",36.0,Town in Nauru.,"[[[-137.444883346558, -43.9588756561279], [-13..."
1868,6644,Yat,Yat,Mars,7.46,18.13,-29.03,18.19,18.07,-28.96,...,Africa,Niger,"Crater, craters",AA,mc11,Approved,1976,36.0,Town in Niger.,"[[[-29.026990890502987, 18.0670261383057], [-2..."
1869,6649,Yebra,Yebra,Mars,4.85,20.79,105.69,20.83,20.75,105.73,...,Europe,Spain,"Crater, craters",AA,mc14,Approved,1988,36.0,Town in Spain.,"[[[105.688375473022, 20.7498455047607], [105.6..."
1870,6650,Yegros,Yegros,Mars,13.98,-22.30,-23.66,-22.18,-22.42,-23.54,...,South and Central America,Paraguay,"Crater, craters",AA,mc19,Approved,1976,36.0,Town in Paraguay.,"[[[-23.663908004761026, -22.4202499389648], [-..."
1871,15032,Yellowknife,Yellowknife,Mars,0.12,-4.58,137.44,-4.58,-4.58,137.44,...,North America,Canada,"Crater, craters",AA,mc23,Approved,"Sep 10, 2012",74.0,"Town in the Northwest Territories, Canada.",[]
1872,6671,Yorktown,Yorktown,Mars,8.01,22.88,-48.65,22.95,22.81,-48.58,...,North America,United States,"Crater, craters",AA,mc10,Approved,1976,36.0,American colonial town (Virginia).,"[[[-48.65008354187, 22.8118762969971], [-48.65..."
1873,6672,Yoro,Yoro,Mars,9.61,22.80,-28.04,22.88,22.72,-27.95,...,South and Central America,Honduras,"Crater, craters",AA,mc11,Approved,1976,36.0,Town in Honduras.,"[[[-28.039140701294002, 22.7197284698486], [-2..."
1874,6681,Yungay,Yungay,Mars,19.69,-43.87,-44.75,-43.70,-44.03,-44.52,...,South and Central America,Peru,"Crater, craters",AA,mc26,Approved,1976,36.0,Town in Peru.,"[[[-44.748991012573015, -44.0332221984863], [-..."
1875,6685,Yuty,Yuty,Mars,19.06,22.16,-34.09,22.32,22.00,-33.92,...,South and Central America,Paraguay,"Crater, craters",AA,mc11,Approved,1976,36.0,Town in Paraguay.,"[[[-34.089700698852994, 21.9985866546631], [-3..."
1876,14212,Zarand,Zarand,Mars,2.78,-3.41,-1.50,-3.39,-3.44,-1.47,...,Asia,Iran,"Crater, craters",AA,mc19,Approved,"Sep 14, 2006",179.0,Town in Iran.,"[[[-1.4967441558840164, -3.43516159057617], [-..."
1877,14337,Zaranj,Zaranj,Mars,27.41,12.09,113.05,12.32,11.86,113.29,...,Asia,Afghanistan,"Crater, craters",AA,mc14,Approved,"Feb 26, 2008",36.0,Town in Afghanistan.,"[[[113.060346603394, 11.8620738983154], [113.0..."
1878,14859,Zarqa Valles,Zarqa Valles,Mars,21.37,0.32,80.59,3.93,-3.45,82.87,...,Asia,Jordan,"Vallis, valles",VA,mc13,Approved,"Jun 13, 2011",74.0,River in Jordan.,[]
1879,6708,Zea Dorsa,Zea Dorsa,Mars,249.02,-48.87,80.54,-47.11,-50.65,83.71,...,Europe,Latin,"Dorsum, dorsa",DO,mc28,Approved,1979,57.0,Classical albedo feature name.,"[[[82.18731880187988, -50.52229881286621], [81..."
1880,6719,Zephyria,Zephyria,Mars,0.00,0.00,165.00,0.00,0.00,165.00,...,Europe,Latin,Albedo Feature,AL,NaN,Approved,1958,60.0,Land of the west wind.,[]
1881,15195,Zephyria Fluctus,Zephyria Fluctus,Mars,42.00,0.72,155.53,0.96,0.51,155.71,...,Europe,Greek,"Fluctus, fluctūs",FL,mc15,Approved,"Jan 17, 2014",71.0,Classical albedo feature name.,[]
1882,6720,Zephyria Mensae,Zephyria Mensae,Mars,333.61,-11.62,171.98,-8.84,-14.38,174.40,...,Europe,Latin,"Mensa, mensae",MN,mc23,Approved,1985,57.0,Albedo feature name.,"[[[172.47260093688965, -8.836355209350586], [1..."
1883,14164,Zephyria Planum,Zephyria Planum,Mars,575.11,-1.08,153.73,3.26,-5.42,156.75,...,Europe,Greek,"Planum, plana",PM,mc23,Approved,2006,71.0,Classical albedo feature name.,"[[[156.00415229797363, -5.415916442871094], [1..."
1884,6721,Zephyria Tholus,Zephyria Tholus,Mars,35.95,-19.75,172.92,-19.44,-20.05,173.20,...,Europe,Latin,"Tholus, tholi",TH,mc23,Approved,1997,57.0,Albedo feature name.,"[[[172.91116905212402, -19.470535278320312], [..."
1885,6722,Zephyrus Fossae,Zephyrus Fossae,Mars,306.19,23.93,144.19,26.48,21.40,145.80,...,Europe,Latin,"Fossa, fossae",FO,mc15,Approved,1985,57.0,Albedo feature name.,"[[[144.96639442443848, 26.35270118713379], [14..."
1886,15689,Zeus Patera,Zeus Patera,Mars,65.00,18.39,-132.93,18.91,17.80,-132.53,...,Europe,Greek,"Patera, paterae",PE,mc09,Approved,"Oct 16, 2017",174.0,"Greek sky, thunder and lightning god, who rule...",[]
1887,6730,Zhigou,Zhigou,Mars,21.86,-29.10,-102.59,-28.96,-29.24,-102.38,...,Asia,China,"Crater, craters",AA,mc17,Approved,1991,74.0,Town in China.,"[[[-102.595331192017, -29.2429676055908], [-10..."
1888,6737,Zilair,Zilair,Mars,46.91,-31.81,-32.94,-31.41,-32.21,-32.46,...,Europe,Russia,"Crater, craters",AA,mc26,Approved,1979,36.0,Town in Russia.,"[[[-32.92231559753401, -32.2054843902588], [-3..."
1889,6743,Zir,Zir,Mars,6.16,18.54,-36.54,18.60,18.49,-36.49,...,Asia,Turkey,"Crater, craters",AA,mc11,Approved,1976,36.0,Town in Turkey.,"[[[-36.541563034058015, 18.4930324554443], [-3..."
1890,6750,Zongo,Zongo,Mars,46.83,-33.76,-41.69,-33.36,-34.15,-41.21,...,Africa,Zaire,"Crater, craters",AA,mc26,Approved,1979,36.0,Town in Zaire.,"[[[-41.677206039428995, -34.1509971618652], [-..."
1891,6946,Žulanka,Zulanka,Mars,43.12,-2.27,-42.16,-1.91,-2.63,-41.80,...,Europe,Russia,"Crater, craters",AA,mc19,Approved,1976,36.0,Town in Russia.,"[[[-42.15385246276901, -2.6348876953125], [-42..."
1892,6951,Zumba,Zumba,Mars,2.93,-28.67,-133.07,-28.64,-28.69,-133.05,...,South and Central America,Ecuador,"Crater, craters",AA,mc17,Approved,2006,179.0,Town in Ecuador.,"[[[-133.073438644409, -28.693208694458], [-133..."
1893,6764,Zuni,Zuni,Mars,24.28,19.22,-29.58,19.43,19.02,-29.36,...,North America,United States,"Crater, craters",AA,mc11,Approved,1976,36.0,"Town in New Mexico, USA.","[[[-29.570692062377987, 19.0184535980225], [-2..."
1894,6765,Zunil,Zunil,Mars,10.26,7.70,166.19,7.79,7.61,166.28,...,South and Central America,Mayan,"Crater, craters",AA,mc15,Approved,2003,173.0,Mayan village in Guatemala.,"[[[166.192293167114, 7.61384010314941], [166.1..."
1895,6768,Zutphen,Zutphen,Mars,38.29,-13.85,174.32,-13.53,-14.18,174.65,...,Europe,Netherlands (Dutch),"Crater, craters",AA,mc23,Approved,2003,36.0,Town in The Netherlands.,"[[[174.326848983765, -14.1758460998535], [174...."

><h1>2. Data Creation 2/3 </h1>
<h3><font color = "Grey">Bibliographic Stats Query </h3>

><h2> Bibliography Stats to collect </h2>
<h3><font color = 'Grey'>1. Number of Papers</h3>
<h3><font color = 'Grey'>2. Number of Citing Papers </h3>
<h3><font color = 'Grey'>3. Number of Self Citations </h3>
<h3><font color = 'Grey'>4. Total Number of Citations </h3>
<h3><font color = 'Grey'>5. Total Number of Refereed Citations </h3>

In [20]:
import ads
q = ads.SearchQuery(q='Abus Vallis', keyword='mars', fl=['bibcode'], rows=2000)
bibcodes = [j.bibcode for j in q]
metrics_query = ads.MetricsQuery(bibcodes)
metrics_response = metrics_query.execute()
metrics_response

{'basic stats': {'average number of downloads': 5.4,
  'average number of reads': 22.8,
  'median number of downloads': 4.0,
  'median number of reads': 7.0,
  'normalized paper count': 2.25,
  'number of papers': 5,
  'recent number of downloads': 0,
  'recent number of reads': 2,
  'total number of downloads': 27,
  'total number of reads': 114},
 'basic stats refereed': {'average number of downloads': 17.0,
  'average number of reads': 50.0,
  'median number of downloads': 17.0,
  'median number of reads': 50.0,
  'normalized paper count': 0.5,
  'number of papers': 1,
  'recent number of downloads': 0,
  'recent number of reads': 1,
  'total number of downloads': 17,
  'total number of reads': 50},
 'citation stats': {'average number of citations': 1.6,
  'average number of refereed citations': 1.2,
  'median number of citations': 0.0,
  'median number of refereed citations': 0.0,
  'normalized number of citations': 3.5,
  'normalized number of refereed citations': 2.5,
  'number of citing papers': 8,
  'number of self-citations': 0,
  'self-citations': [],
  'total number of citations': 8,
  'total number of refereed citations': 6},
 'citation stats refereed': {'average number of citations': 6.0,
  'average number of refereed citations': 4.0,
  'median number of citations': 6.0,
  'median number of refereed citations': 4.0,
  'normalized number of citations': 3.0,
  'normalized number of refereed citations': 2.0,
  'number of citing papers': 6,
  'number of self-citations': 0,
  'total number of citations': 6,
  'total number of refereed citations': 4},
 'histograms': {'citations': {'nonrefereed to nonrefereed': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'nonrefereed to nonrefereed normalized': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'nonrefereed to refereed': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 2,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'nonrefereed to refereed normalized': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 1.0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed to nonrefereed': {'1987': 1,
    '1988': 0,
    '1989': 0,
    '1990': 1,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed to nonrefereed normalized': {'1987': 0.25,
    '1988': 0,
    '1989': 0,
    '1990': 0.25,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed to refereed': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 1,
    '1994': 0,
    '1995': 0,
    '1996': 1,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 1,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 1,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed to refereed normalized': {'1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0,
    '1991': 0,
    '1992': 0,
    '1993': 0.5,
    '1994': 0,
    '1995': 0,
    '1996': 0.5,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0.5,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0.5,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0}},
  'downloads': {'all downloads': {'1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 1,
    '2001': 0,
    '2002': 3,
    '2003': 0,
    '2004': 1,
    '2005': 0,
    '2006': 4,
    '2007': 4,
    '2008': 3,
    '2009': 2,
    '2010': 2,
    '2011': 1,
    '2012': 3,
    '2013': 2,
    '2014': 1,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'all downloads normalized': {'1996': 0.0,
    '1997': 0.0,
    '1998': 0.0,
    '1999': 0.0,
    '2000': 0.25,
    '2001': 0.0,
    '2002': 1.5,
    '2003': 0.0,
    '2004': 1.0,
    '2005': 0.0,
    '2006': 2.5,
    '2007': 1.75,
    '2008': 1.5,
    '2009': 1.0,
    '2010': 1.0,
    '2011': 0.5,
    '2012': 1.5,
    '2013': 1.0,
    '2014': 0.5,
    '2015': 0.0,
    '2016': 0.0,
    '2017': 0.0},
   'refereed downloads': {'1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 3,
    '2008': 3,
    '2009': 2,
    '2010': 2,
    '2011': 1,
    '2012': 3,
    '2013': 2,
    '2014': 1,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed downloads normalized': {'1996': 0.0,
    '1997': 0.0,
    '1998': 0.0,
    '1999': 0.0,
    '2000': 0.0,
    '2001': 0.0,
    '2002': 0.0,
    '2003': 0.0,
    '2004': 0.0,
    '2005': 0.0,
    '2006': 0.0,
    '2007': 1.5,
    '2008': 1.5,
    '2009': 1.0,
    '2010': 1.0,
    '2011': 0.5,
    '2012': 1.5,
    '2013': 1.0,
    '2014': 0.5,
    '2015': 0.0,
    '2016': 0.0,
    '2017': 0.0}},
  'publications': {'all publications': {'1986': 1,
    '1987': 0,
    '1988': 1,
    '1989': 0,
    '1990': 1,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 1,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 1,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'all publications normalized': {'1986': 0.25,
    '1987': 0,
    '1988': 1.0,
    '1989': 0,
    '1990': 0.5,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0.16666666666666666,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0.3333333333333333,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed publications': {'1986': 0,
    '1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 1,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0},
   'refereed publications normalized': {'1986': 0,
    '1987': 0,
    '1988': 0,
    '1989': 0,
    '1990': 0.5,
    '1991': 0,
    '1992': 0,
    '1993': 0,
    '1994': 0,
    '1995': 0,
    '1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 0,
    '2005': 0,
    '2006': 0,
    '2007': 0,
    '2008': 0,
    '2009': 0,
    '2010': 0,
    '2011': 0,
    '2012': 0,
    '2013': 0,
    '2014': 0,
    '2015': 0,
    '2016': 0,
    '2017': 0}},
  'reads': {'all reads': {'1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 1,
    '2001': 0,
    '2002': 3,
    '2003': 11,
    '2004': 14,
    '2005': 5,
    '2006': 11,
    '2007': 24,
    '2008': 5,
    '2009': 6,
    '2010': 11,
    '2011': 1,
    '2012': 5,
    '2013': 4,
    '2014': 5,
    '2015': 3,
    '2016': 3,
    '2017': 2},
   'all reads normalized': {'1996': 0.0,
    '1997': 0.0,
    '1998': 0.0,
    '1999': 0.0,
    '2000': 0.25,
    '2001': 0.0,
    '2002': 1.5,
    '2003': 1.8333333333333333,
    '2004': 3.833333333333333,
    '2005': 2.0,
    '2006': 4.666666666666667,
    '2007': 9.166666666666666,
    '2008': 2.1666666666666665,
    '2009': 2.3333333333333335,
    '2010': 4.833333333333333,
    '2011': 0.5,
    '2012': 2.1666666666666665,
    '2013': 2.0,
    '2014': 1.8333333333333333,
    '2015': 1.3333333333333333,
    '2016': 0.6666666666666666,
    '2017': 0.8333333333333333},
   'refereed reads': {'1996': 0,
    '1997': 0,
    '1998': 0,
    '1999': 0,
    '2000': 0,
    '2001': 0,
    '2002': 0,
    '2003': 0,
    '2004': 2,
    '2005': 1,
    '2006': 3,
    '2007': 15,
    '2008': 4,
    '2009': 4,
    '2010': 9,
    '2011': 1,
    '2012': 4,
    '2013': 4,
    '2014': 2,
    '2015': 0,
    '2016': 0,
    '2017': 1},
   'refereed reads normalized': {'1996': 0.0,
    '1997': 0.0,
    '1998': 0.0,
    '1999': 0.0,
    '2000': 0.0,
    '2001': 0.0,
    '2002': 0.0,
    '2003': 0.0,
    '2004': 1.0,
    '2005': 0.5,
    '2006': 1.5,
    '2007': 7.5,
    '2008': 2.0,
    '2009': 2.0,
    '2010': 4.5,
    '2011': 0.5,
    '2012': 2.0,
    '2013': 2.0,
    '2014': 1.0,
    '2015': 0.0,
    '2016': 0.0,
    '2017': 0.5}}},
 'indicators': {'g': 2,
  'h': 2,
  'i10': 0,
  'i100': 0,
  'm': 0.0625,
  'read10': 0.3466286799620133,
  'riq': 15,
  'tori': 0.17846076454906004},
 'indicators refereed': {'g': 1,
  'h': 1,
  'i10': 0,
  'i100': 0,
  'm': 0.03125,
  'read10': 0.0,
  'riq': 15,
  'tori': 0.1644285064845439},
 'skipped bibcodes': [],
 'time series': {'g': {'1986': 0,
   '1987': 0,
   '1988': 0,
   '1989': 0,
   '1990': 1,
   '1991': 1,
   '1992': 1,
   '1993': 1,
   '1994': 1,
   '1995': 1,
   '1996': 1,
   '1997': 1,
   '1998': 1,
   '1999': 1,
   '2000': 1,
   '2001': 1,
   '2002': 1,
   '2003': 1,
   '2004': 1,
   '2005': 1,
   '2006': 1,
   '2007': 1,
   '2008': 1,
   '2009': 1,
   '2010': 1,
   '2011': 1,
   '2012': 1,
   '2013': 1,
   '2014': 1,
   '2015': 1,
   '2016': 1,
   '2017': 1},
  'h': {'1986': 0,
   '1987': 0,
   '1988': 0,
   '1989': 0,
   '1990': 0,
   '1991': 0,
   '1992': 0,
   '1993': 1,
   '1994': 1,
   '1995': 1,
   '1996': 1,
   '1997': 1,
   '1998': 1,
   '1999': 1,
   '2000': 1,
   '2001': 1,
   '2002': 1,
   '2003': 1,
   '2004': 1,
   '2005': 1,
   '2006': 1,
   '2007': 1,
   '2008': 1,
   '2009': 1,
   '2010': 1,
   '2011': 1,
   '2012': 1,
   '2013': 1,
   '2014': 1,
   '2015': 1,
   '2016': 1,
   '2017': 1},
  'i10': {'1986': 0,
   '1987': 0,
   '1988': 0,
   '1989': 0,
   '1990': 0,
   '1991': 0,
   '1992': 0,
   '1993': 0,
   '1994': 0,
   '1995': 0,
   '1996': 0,
   '1997': 0,
   '1998': 0,
   '1999': 0,
   '2000': 0,
   '2001': 0,
   '2002': 0,
   '2003': 0,
   '2004': 0,
   '2005': 0,
   '2006': 0,
   '2007': 0,
   '2008': 0,
   '2009': 0,
   '2010': 0,
   '2011': 0,
   '2012': 0,
   '2013': 0,
   '2014': 0,
   '2015': 0,
   '2016': 0,
   '2017': 0},
  'i100': {'1986': 0,
   '1987': 0,
   '1988': 0,
   '1989': 0,
   '1990': 0,
   '1991': 0,
   '1992': 0,
   '1993': 0,
   '1994': 0,
   '1995': 0,
   '1996': 0,
   '1997': 0,
   '1998': 0,
   '1999': 0,
   '2000': 0,
   '2001': 0,
   '2002': 0,
   '2003': 0,
   '2004': 0,
   '2005': 0,
   '2006': 0,
   '2007': 0,
   '2008': 0,
   '2009': 0,
   '2010': 0,
   '2011': 0,
   '2012': 0,
   '2013': 0,
   '2014': 0,
   '2015': 0,
   '2016': 0,
   '2017': 0},
  'read10': {'1986': 0.0,
   '1987': 0.0,
   '1988': 0.0,
   '1989': 0.0,
   '1990': 0.0,
   '1991': 0.0,
   '1992': 0.0,
   '1993': 0.0,
   '1994': 0.0,
   '1995': 0.0,
   '1996': 0.0,
   '1997': 0.0,
   '1998': 0.0,
   '1999': 0.0,
   '2000': 0,
   '2001': 0,
   '2002': 0.0,
   '2003': 1.8333333333333333,
   '2004': 1.8333333333333333,
   '2005': 0.5,
   '2006': 0.6666666666666666,
   '2007': 1.1666666666666667,
   '2008': 0.16666666666666666,
   '2009': 0.3333333333333333,
   '2010': 0.3333333333333333,
   '2011': 0.0,
   '2012': 0.0,
   '2013': 0.0,
   '2014': 0.6666666666666666,
   '2015': 0.0,
   '2016': 0.3333333333333333,
   '2017': 0.3466286799620133},
  'tori': {'1986': 0.0,
   '1987': 0.004032258064516129,
   '1988': 0.004032258064516129,
   '1989': 0.004032258064516129,
   '1990': 0.014032258064516129,
   '1991': 0.014032258064516129,
   '1992': 0.014032258064516129,
   '1993': 0.024670555936856554,
   '1994': 0.024670555936856554,
   '1995': 0.024670555936856554,
   '1996': 0.029621050986361502,
   '1997': 0.029621050986361502,
   '1998': 0.029621050986361502,
   '1999': 0.029621050986361502,
   '2000': 0.029621050986361502,
   '2001': 0.0329323092645072,
   '2002': 0.0329323092645072,
   '2003': 0.0329323092645072,
   '2004': 0.0329323092645072,
   '2005': 0.0329323092645072,
   '2006': 0.0329323092645072,
   '2007': 0.17846076454906004,
   '2008': 0.17846076454906004,
   '2009': 0.17846076454906004,
   '2010': 0.17846076454906004,
   '2011': 0.17846076454906004,
   '2012': 0.17846076454906004,
   '2013': 0.17846076454906004,
   '2014': 0.17846076454906004,
   '2015': 0.17846076454906004,
   '2016': 0.17846076454906004,
   '2017': 0.17846076454906004}}}

><li><h2>Publication Year Division</h2></li>
><h3><font color = 'Grey'>1970 / 1971-1980 / 1981-1990 / 1991-2000 / 2001-2010 / 2011-2015 / 2016-2017</h3>

In [ ]:
# Retrieve bibliography stats from 2016 to 2017
np2016_2017 = []
ncp2016_2017 = []
nsc2016_2017 = []
tnc2016_2017 = []
tnrc2016_2017 = []

for i in attr_feature['Clean_Feature_Name']:
    query_string = str(i) + " pubdate:[2016-01 TO 2017-12]"
    q = ads.SearchQuery(q= query_string, keyword='mars', fl=['bibcode'], rows= 3000)
    bibcodes = [j.bibcode for j in q]
    metrics_query = ads.MetricsQuery(bibcodes)
    try:        
        metrics_response = metrics_query.execute()
        np = metrics_response['basic stats']['number of papers']
        ncp = metrics_response['citation stats']['number of citing papers']
        nsc = metrics_response['citation stats']['number of self-citations']
        tnc = metrics_response['citation stats']['total number of citations']
        tnrc = metrics_response['citation stats']['total number of refereed citations']
        np2016_2017.append(np)
        ncp2016_2017.append(ncp)
        nsc2016_2017.append(nsc)
        tnc2016_2017.append(tnc)
        tnrc2016_2017.append(tnrc)
        print(i +" added")
    except:
        np2016_2017.append(0)
        ncp2016_2017.append(0)
        nsc2016_2017.append(0)
        tnc2016_2017.append(0)
        tnrc2016_2017.append(0)        
        print(i +" added with exception")

><li><h2>Landing Site</h2></li>

><li><h2>GeoJson with Polygon Creation</h2></li>

In [ ]:
landing_site=[]
for i in attr_feature['Clean_Feature_Name']:
    q = ads.SearchQuery(q=i, keyword='landing site mars', fl=['bibcode'], rows=1)
    bibcodes = [j.bibcode for j in q]
    metrics_query=ads.MetricsQuery(bibcodes)
    try:
        metrics_response = metrics_query.execute()
        landing_site.append(1)
        print(i + " landing site added")
    except:
        landing_site.append(0)
        print(i + " no landing site added")

In [24]:
data_frame2 = pd.read_csv('data/mars_gaz_table.csv', index_col = False)
data_frame2

,Feature_ID,Clean_Feature_Name,Target,Diameter,Center_Latitude,Center_Longitude,Northern_Latitude,Southern_Latitude,Eastern_Longitude,Western_Longitude,...,number_of_self_citations_2016_2017,total_number_of_citations_2016_2017,total_number_of_refereed citations_2016_2017,number_of_papers,number_of_citing papers,number_of_self-citations,total_number_of_citations,total_number_of_refereed citations,landing_site,polygon
0,4,Abalos Colles,Mars,235.83,76.83,-71.65,78.78,74.81,-66.61,-75.46,...,0,6,3,4,144,1,144,123,0,"[[[-68.42836570739746, 74.97826194763184], [-6..."
1,14147,Abalos Mensa,Mars,129.18,81.17,-75.60,82.40,80.21,-69.48,-80.66,...,0,0,0,11,210,10,216,179,0,"[[[-73.63830757141113, 80.26974678039551], [-7..."
2,14148,Abalos Scopuli,Mars,109.16,80.72,-76.56,81.96,80.20,-69.48,-80.53,...,0,2,1,3,10,0,11,8,0,"[[[-74.60061454772949, 80.95564079284668], [-7..."
3,5,Abalos Undae,Mars,442.74,78.52,-87.50,82.20,74.94,-76.97,-98.60,...,0,2,1,6,49,1,49,38,0,"[[[-80.35336875915527, 80.58683967590332], [-7..."
4,6,Aban,Mars,4.28,15.91,111.10,15.94,15.87,111.14,111.06,...,0,0,0,1,6,0,6,3,0,"[[[111.101976394653, 15.8708324432373], [111.1..."
5,25,Abus Vallis,Mars,60.99,-5.49,-147.20,-5.02,-5.99,-147.16,-147.28,...,0,0,0,5,8,0,8,6,0,[]
6,31,Achar,Mars,5.36,45.43,123.16,45.48,45.39,123.23,123.10,...,0,0,0,1,4,0,4,3,0,"[[[123.165567398071, 45.3864192962646], [123.1..."
7,34,Acheron Catena,Mars,421.77,37.47,-100.80,40.70,33.51,-98.29,-103.29,...,0,0,0,8,115,2,119,93,0,[]
8,35,Acheron Fossae,Mars,703.11,38.27,-135.02,40.03,31.47,-129.08,-143.10,...,0,2,1,63,1880,92,2590,2185,0,"[[[-129.68730354309082, 37.86834907531738], [-..."
9,36,Acidalia Colles,Mars,356.30,50.34,-23.09,52.96,48.42,-19.63,-28.23,...,0,5,5,24,988,23,1220,1094,0,"[[[-19.97706413269043, 51.070783615112305], [-..."
10,37,Acidalia Mensa,Mars,226.86,46.69,-25.34,48.69,45.03,-22.97,-28.19,...,0,13,11,83,2313,272,3839,3230,0,"[[[-23.437543869018555, 47.826555252075195], [..."
11,38,Acidalia Planitia,Mars,3362.97,49.76,-20.74,68.67,14.76,15.00,-55.00,...,7,87,80,341,4772,1059,10072,8697,1,"[[[1.239706039428711, 39.644025802612305], [0...."
12,14182,Ada,Mars,2.09,-3.06,-3.22,-3.04,-3.08,-3.21,-3.24,...,0,31,31,78,2267,57,3039,2584,0,"[[[-3.2239589691159836, -3.07810401916504], [-..."
13,45,Adamas Labyrinthus,Mars,853.00,35.70,105.12,41.07,30.34,111.46,96.27,...,0,0,0,5,82,0,86,70,0,"[[[105.58868598937988, 38.07891273498535], [10..."
14,46,Adams,Mars,90.22,30.91,163.10,31.68,30.15,163.99,162.22,...,2,39,34,496,8330,2174,17626,15306,1,"[[[163.118543624878, 30.1533336639404], [163.1..."
15,65,Aeolis,Mars,0.00,-4.94,145.00,-4.94,-4.94,145.00,145.00,...,95,456,435,2309,12833,12505,46824,40451,1,[]
16,15019,Aeolis Dorsa,Mars,459.17,-5.05,152.63,-1.03,-8.13,156.42,148.60,...,6,36,30,76,1284,123,1819,1556,0,[]
17,66,Aeolis Mensae,Mars,785.09,-3.25,140.63,2.07,-6.56,146.95,135.33,...,6,60,50,211,3872,838,7968,6625,1,"[[[140.39999961853027, -0.733449935913086], [1..."
18,15000,Aeolis Mons,Mars,88.99,-5.08,137.85,-4.46,-5.61,138.62,137.11,...,37,235,224,591,7325,2474,18154,15465,1,[]
19,15001,Aeolis Palus,Mars,111.63,-4.47,137.42,-4.18,-5.39,138.65,136.75,...,22,111,106,149,2305,236,3657,3070,1,[]
20,14165,Aeolis Planum,Mars,852.81,-1.14,144.76,4.40,-6.68,149.98,139.08,...,31,253,235,751,7258,3753,19922,17262,1,"[[[145.30062675476074, 1.135274887084961], [14..."
21,15031,Aeolis Serpens,Mars,538.55,-1.38,149.57,2.48,-4.90,152.00,147.68,...,1,21,20,375,6402,1406,14071,11885,1,[]
22,68,Aeria,Mars,0.00,9.88,50.00,9.88,9.88,50.00,50.00,...,0,0,0,25,88,6,124,114,0,[]
23,69,Aesacus Dorsum,Mars,276.69,36.82,153.15,38.69,34.70,154.72,152.28,...,0,0,0,0,0,0,0,0,0,[]
24,71,Aetheria,Mars,0.00,39.67,130.00,39.67,39.67,130.00,130.00,...,0,0,0,15,67,1,68,60,0,[]
25,72,Aethiopis,Mars,0.00,9.88,130.00,9.88,9.88,130.00,130.00,...,0,0,0,11,24,0,27,23,0,[]
26,79,Aganippe Fossa,Mars,537.16,-8.49,-126.00,-4.06,-12.85,-124.77,-126.86,...,0,0,0,1,5,0,5,5,0,[]
27,81,Agassiz,Mars,108.77,-69.88,-88.89,-68.97,-70.80,-86.20,-91.54,...,0,0,0,14,337,4,351,317,0,"[[[-88.81912803649902, -70.80104637146], [-88...."
28,114,Airy,Mars,43.05,-5.14,0.05,-4.77,-5.50,0.42,-0.31,...,56,398,377,1964,15036,5988,38336,34503,1,"[[[0.064416042621541, -5.500483014882271], [0...."
29,115,Airy 0,Mars,0.79,-5.07,0.00,-5.07,-5.08,0.01,-0.01,...,44,390,369,1576,14046,5047,34157,30812,1,"[[[0.001520156860352, -5.080926895141602], [0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1866,6640,Yar,Mars,6.18,22.27,-39.15,22.32,22.22,-39.09,-39.20,...,0,0,0,3,59,0,59,52,0,"[[[-39.147054672240984, 22.2179393768311], [-3..."
1867,14625,Yaren,Mars,9.19,-43.88,-137.45,-43.80,-43.96,-137.34,-137.55,...,0,0,0,0,0,0,0,0,0,"[[[-137.444883346558, -43.9588756561279], [-13..."
1868,6644,Yat,Mars,7.46,18.13,-29.03,18.19,18.07,-28.96,-29.09,...,0,0,0,0,0,0,0,0,0,"[[[-29.026990890502987, 18.0670261383057], [-2..."
1869,6649,Yebra,Mars,4.85,20.79,105.69,20.83,20.75,105.73,105.64,...,0,0,0,0,0,0,0,0,0,"[[[105.688375473022, 20.7498455047607], [105.6..."
1870,6650,Yegros,Mars,13.98,-22.30,-23.66,-22.18,-22.42,-23.54,-23.79,...,0,0,0,0,0,0,0,0,0,"[[[-23.663908004761026, -22.4202499389648], [-..."
1871,15032,Yellowknife,Mars,0.12,-4.58,137.44,-4.58,-4.58,137.44,137.44,...,34,265,253,189,687,345,1427,1289,0,[]
1872,6671,Yorktown,Mars,8.01,22.88,-48.65,22.95,22.81,-48.58,-48.72,...,0,0,0,16,211,7,236,199,1,"[[[-48.65008354187, 22.8118762969971], [-48.65..."
1873,6672,Yoro,Mars,9.61,22.80,-28.04,22.88,22.72,-27.95,-28.13,...,0,0,0,0,0,0,0,0,0,"[[[-28.039140701294002, 22.7197284698486], [-2..."
1874,6681,Yungay,Mars,19.69,-43.87,-44.75,-43.70,-44.03,-44.52,-44.98,...,0,0,0,25,177,14,242,217,0,"[[[-44.748991012573015, -44.0332221984863], [-..."
1875,6685,Yuty,Mars,19.06,22.16,-34.09,22.32,22.00,-33.92,-34.27,...,0,0,0,12,500,2,569,497,0,"[[[-34.089700698852994, 21.9985866546631], [-3..."
1876,14212,Zarand,Mars,2.78,-3.41,-1.50,-3.39,-3.44,-1.47,-1.52,...,0,0,0,0,0,0,0,0,0,"[[[-1.4967441558840164, -3.43516159057617], [-..."
1877,14337,Zaranj,Mars,27.41,12.09,113.05,12.32,11.86,113.29,112.82,...,0,0,0,0,0,0,0,0,0,"[[[113.060346603394, 11.8620738983154], [113.0..."
1878,14859,Zarqa Valles,Mars,21.37,0.32,80.59,3.93,-3.45,82.87,76.60,...,0,0,0,1,15,0,15,13,0,[]
1879,6708,Zea Dorsa,Mars,249.02,-48.87,80.54,-47.11,-50.65,83.71,77.38,...,0,9,9,1,9,0,9,9,0,"[[[82.18731880187988, -50.52229881286621], [81..."
1880,6719,Zephyria,Mars,0.00,0.00,165.00,0.00,0.00,165.00,165.00,...,0,13,10,51,817,46,949,816,0,[]
1881,15195,Zephyria Fluctus,Mars,42.00,0.72,155.53,0.96,0.51,155.71,155.29,...,0,0,0,0,0,0,0,0,0,[]
1882,6720,Zephyria Mensae,Mars,333.61,-11.62,171.98,-8.84,-14.38,174.40,169.23,...,0,8,5,13,276,11,288,218,0,"[[[172.47260093688965, -8.836355209350586], [1..."
1883,14164,Zephyria Planum,Mars,575.11,-1.08,153.73,3.26,-5.42,156.75,149.96,...,0,13,10,25,642,28,692,594,0,"[[[156.00415229797363, -5.415916442871094], [1..."
1884,6721,Zephyria Tholus,Mars,35.95,-19.75,172.92,-19.44,-20.05,173.20,172.61,...,0,7,4,10,437,5,464,425,0,"[[[172.91116905212402, -19.470535278320312], [..."
1885,6722,Zephyrus Fossae,Mars,306.19,23.93,144.19,26.48,21.40,145.80,142.83,...,0,0,0,3,1,0,2,2,0,"[[[144.96639442443848, 26.35270118713379], [14..."
1886,15689,Zeus Patera,Mars,65.00,18.39,-132.93,18.91,17.80,-132.53,-133.51,...,0,0,0,4,9,0,10,10,0,[]
1887,6730,Zhigou,Mars,21.86,-29.10,-102.59,-28.96,-29.24,-102.38,-102.80,...,0,0,0,0,0,0,0,0,0,"[[[-102.595331192017, -29.2429676055908], [-10..."
1888,6737,Zilair,Mars,46.91,-31.81,-32.94,-31.41,-32.21,-32.46,-33.40,...,0,0,0,0,0,0,0,0,0,"[[[-32.92231559753401, -32.2054843902588], [-3..."
1889,6743,Zir,Mars,6.16,18.54,-36.54,18.60,18.49,-36.49,-36.60,...,0,0,0,4,23,0,23,22,0,"[[[-36.541563034058015, 18.4930324554443], [-3..."
1890,6750,Zongo,Mars,46.83,-33.76,-41.69,-33.36,-34.15,-41.21,-42.16,...,0,0,0,0,0,0,0,0,0,"[[[-41.677206039428995, -34.1509971618652], [-..."
1891,6946,Zulanka,Mars,43.12,-2.27,-42.16,-1.91,-2.63,-41.80,-42.52,...,0,0,0,0,0,0,0,0,0,"[[[-42.15385246276901, -2.6348876953125], [-42..."
1892,6951,Zumba,Mars,2.93,-28.67,-133.07,-28.64,-28.69,-133.05,-133.10,...,0,2,2,8,93,3,115,95,0,"[[[-133.073438644409, -28.693208694458], [-133..."
1893,6764,Zuni,Mars,24.28,19.22,-29.58,19.43,19.02,-29.36,-29.79,...,0,0,0,0,0,0,0,0,0,"[[[-29.570692062377987, 19.0184535980225], [-2..."
1894,6765,Zunil,Mars,10.26,7.70,166.19,7.79,7.61,166.28,166.10,...,0,6,5,61,1069,82,1469,1289,0,"[[[166.192293167114, 7.61384010314941], [166.1..."
1895,6768,Zutphen,Mars,38.29,-13.85,174.32,-13.53,-14.18,174.65,173.99,...,0,0,0,4,61,1,61,56,0,"[[[174.326848983765, -14.1758460998535], [174...."

[Initial map link](https://shinjjo.carto.com/builder/e90660bf-7882-400b-be20-c35ed8c8ffc2/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B-80.11856387883782%2C-309.37500000000006%5D%2C%22sw%22%3A%5B85.45805784937232%2C185.27343750000003%5D%2C%22center%22%3A%5B21.779905342529645%2C-62.05078125000001%5D%2C%22zoom%22%3A2%7D%2C%22widgets%22%3A%7B%220ed24f9f-6d6f-454f-aa0a-93a1e81ebf2d%22%3A%7B%22autoStyle%22%3Atrue%7D%2C%22b1acfd93-a97b-42b3-997e-8a762cee31b1%22%3A%7B%22normalized%22%3Atrue%7D%2C%22c71bed88-3cb6-4403-ad4f-8ea792619102%22%3A%7B%22acceptedCategories%22%3A%5B%221%22%5D%7D%7D%7D)

> <h1>1. Data Creation 3/3</h1>
> <h2><font color="Grey">List of Publication Data</h2>

In [ ]:
cno = 0
Papers = []
for i, j in zip(attr['Clean_Feature_Name'], range(len(attr))):
    q = ads.SearchQuery(q=i, keyword='mars', fl=['bibcode', 'title', 'author', 'year', 'pub', 'ciation_count'], rows = 2000)
    fid = attr['Feature_ID'][j] 
    cfn = attr['Clean_Feature_Name'][j] 
    ft = attr['Feature_Type'][j] 
    ftc = attr['Feature_Type_Code'][j]
    for p in q:
        article = (fid, cfn, ft, ftc, p.title, p.author, p.year, p.bibcode, p.pub, p.citation_count)
        Papers.append(article)
    cno += 1
    print(str(cno) + i + " info added ")

In [28]:
paper = pd.read_csv('paper.csv', index_col = False)
paper

,Feature_ID,Clean_Feature_Name,Feature_Type,Feature_Type_Code,title,author,year,bibcode,pub
0,4,Abalos Colles,"Collis, colles",CO,['Arecibo radar imagery of Mars: II. Chryse-Xa...,"['Harmon, John K.', 'Nolan, Michael C.']",2017,2017Icar..281..162H,Icarus
1,4,Abalos Colles,"Collis, colles",CO,['Resurfacing history of the northern plains o...,"['Tanaka, K. L.', 'Skinner, J. A.', 'Hare, T. ...",2003,2003JGRE..108.8043T,Journal of Geophysical Research (Planets)
2,4,Abalos Colles,"Collis, colles",CO,['Formation constraints on Martian north polar...,"['Fagan, A. L.', 'Sakimoto, S. E. H.', 'Hughes...",2010,2010JGRE..115.7013F,Journal of Geophysical Research (Planets)
3,4,Abalos Colles,"Collis, colles",CO,['Evolution of major sedimentary mounds on Mar...,"['Kite, Edwin S.', 'Sneed, Jonathan', 'Mayer, ...",2016,2016JGRE..121.2282K,Journal of Geophysical Research (Planets)
4,14147,Abalos Mensa,"Mensa, mensae",MN,"['Orbital radar, imagery, and atmospheric mode...","['Brothers, T. C.', 'Holt, J. W.', 'Spiga, A.']",2013,2013GeoRL..40.1334B,Geophysical Research Letters
5,14147,Abalos Mensa,"Mensa, mensae",MN,['Resurfacing history of the northern plains o...,"['Tanaka, K. L.', 'Skinner, J. A.', 'Hare, T. ...",2003,2003JGRE..108.8043T,Journal of Geophysical Research (Planets)
6,14147,Abalos Mensa,"Mensa, mensae",MN,['Interannual and seasonal changes in the nort...,"['Calvin, W. M.', 'James, P. B.', 'Cantor, B. ...",2015,2015Icar..251..181C,Icarus
7,14147,Abalos Mensa,"Mensa, mensae",MN,['Evolution of major sedimentary mounds on Mar...,"['Kite, Edwin S.', 'Sneed, Jonathan', 'Mayer, ...",2016,2016JGRE..121.2282K,Journal of Geophysical Research (Planets)
8,14147,Abalos Mensa,"Mensa, mensae",MN,['Arecibo radar imagery of Mars: II. Chryse-Xa...,"['Harmon, John K.', 'Nolan, Michael C.']",2017,2017Icar..281..162H,Icarus
9,14147,Abalos Mensa,"Mensa, mensae",MN,"['Planum Boreum basal unit topography, Mars: I...","['Brothers, T. C.', 'Holt, J. W.', 'Spiga, A.']",2015,2015JGRE..120.1357B,Journal of Geophysical Research (Planets)
10,14147,Abalos Mensa,"Mensa, mensae",MN,['Aeolian processes as drivers of landform evo...,"['Smith, Isaac B.', 'Spiga, Aymeric', 'Holt, J...",2015,2015Geomo.240...54S,Geomorphology
11,14147,Abalos Mensa,"Mensa, mensae",MN,['Three-dimensional structure and origin of a ...,"['Brothers, T. Charles', 'Holt, John W.']",2016,2016GeoRL..43.1443B,Geophysical Research Letters
12,14147,Abalos Mensa,"Mensa, mensae",MN,['Distribution of hydrated minerals in the nor...,"['Horgan, B. H.', 'Bell, J. F.', 'Noe Dobrea, ...",2009,2009JGRE..114.1005H,Journal of Geophysical Research (Planets)
13,14147,Abalos Mensa,"Mensa, mensae",MN,['Martian north polar cap summer water cycle'],"['Brown, Adrian J.', 'Calvin, Wendy M.', 'Bece...",2016,2016Icar..277..401B,Icarus
14,14147,Abalos Mensa,"Mensa, mensae",MN,"['Stratigraphy of Aeolis Dorsa, Mars: Stratigr...","['Kite, Edwin S.', 'Howard, Alan D.', 'Lucas, ...",2015,2015Icar..253..223K,Icarus
15,14148,Abalos Scopuli,"Scopulus, scopuli",SC,['Interannual and seasonal changes in the nort...,"['Calvin, W. M.', 'James, P. B.', 'Cantor, B. ...",2015,2015Icar..251..181C,Icarus
16,14148,Abalos Scopuli,"Scopulus, scopuli",SC,['Aeolian processes as drivers of landform evo...,"['Smith, Isaac B.', 'Spiga, Aymeric', 'Holt, J...",2015,2015Geomo.240...54S,Geomorphology
17,14148,Abalos Scopuli,"Scopulus, scopuli",SC,['Martian north polar cap summer water cycle'],"['Brown, Adrian J.', 'Calvin, Wendy M.', 'Bece...",2016,2016Icar..277..401B,Icarus
18,5,Abalos Undae,"Unda, undae",UN,['Arecibo radar imagery of Mars: II. Chryse-Xa...,"['Harmon, John K.', 'Nolan, Michael C.']",2017,2017Icar..281..162H,Icarus
19,5,Abalos Undae,"Unda, undae",UN,"['Planum Boreum basal unit topography, Mars: I...","['Brothers, T. C.', 'Holt, J. W.', 'Spiga, A.']",2015,2015JGRE..120.1357B,Journal of Geophysical Research (Planets)
20,5,Abalos Undae,"Unda, undae",UN,['Interannual and seasonal changes in the nort...,"['Calvin, W. M.', 'James, P. B.', 'Cantor, B. ...",2015,2015Icar..251..181C,Icarus
21,5,Abalos Undae,"Unda, undae",UN,['Distribution of hydrated minerals in the nor...,"['Horgan, B. H.', 'Bell, J. F.', 'Noe Dobrea, ...",2009,2009JGRE..114.1005H,Journal of Geophysical Research (Planets)
22,5,Abalos Undae,"Unda, undae",UN,['Martian north polar cap summer water cycle'],"['Brown, Adrian J.', 'Calvin, Wendy M.', 'Bece...",2016,2016Icar..277..401B,Icarus
23,5,Abalos Undae,"Unda, undae",UN,['Formation constraints on Martian north polar...,"['Fagan, A. L.', 'Sakimoto, S. E. H.', 'Hughes...",2010,2010JGRE..115.7013F,Journal of Geophysical Research (Planets)
24,6,Aban,"Crater, craters",AA,['Synthetic and Natural Nakhla Pyroxenes: Pare...,"['McKay, G.', 'Le, L.', 'Wagstaff, J.']",1994,1994LPI....25..883M,Lunar and Planetary Science Conference
25,25,Abus Vallis,"Vallis, valles",VA,"['The Northwestern Slope Valleys Region, Mars:...","['Dohm, J. M.', 'Ferris, J. C.', 'Anderson, R....",2002,2002AGUFM.P71A0446D,AGU Fall Meeting Abstracts
26,25,Abus Vallis,"Vallis, valles",VA,['Small valleys and hydrologic history of the ...,"['Chapman, M. G.', 'Tanaka, K. L.']",1990,1990LPSC...20..531C,Lunar and Planetary Science Conference Proceed...
27,25,Abus Vallis,"Vallis, valles",VA,['Ages of Rocks and Channels in Prospective Ma...,"['Masursky, H.', 'Chapman, M. G.', 'Dial, A. L...",1986,1986LPI....17..520M,Lunar and Planetary Science Conference
28,25,Abus Vallis,"Vallis, valles",VA,['Valley Terminal Deposits: The Martian Sedime...,"['de Hon, R. A.']",1988,1988LPI....19..263D,Lunar and Planetary Science Conference
29,25,Abus Vallis,"Vallis, valles",VA,['Regularity of Baroclinic Waves in the Atmosp...,"['Mooring, T. A.', 'Wilson, R.', 'Vallis, G. K.']",2012,2012AGUFM.P21G..07M,AGU Fall Meeting Abstracts
...,...,...,...,...,...,...,...,...,...
140967,6765,Zunil,"Crater, craters",AA,['Mechanisms and timescales of fluvial activit...,"['Goddard, Kate', 'Warner, Nicholas H.', 'Gupt...",2014,2014JGRE..119..604G,Journal of Geophysical Research (Planets)
140968,6765,Zunil,"Crater, craters",AA,['Evidence for an explosive origin of central ...,"['Williams, Nathan R.', 'Bell, James F.', 'Chr...",2015,2015Icar..252..175W,Icarus
140969,6765,Zunil,"Crater, craters",AA,['Meteoritic evidence for a previously unrecog...,"['Usui, Tomohiro', ""Alexander, Conel M. O'D."",...",2015,2015E&PSL.410..140U,Earth and Planetary Science Letters
140970,6765,Zunil,"Crater, craters",AA,['Possible evidence of paleomarsquakes from fa...,"['Roberts, Gerald P.', 'Matthews, Brian', 'Bri...",2012,2012JGRE..117.2009R,Journal of Geophysical Research (Planets)
140971,6765,Zunil,"Crater, craters",AA,['Crater population and resurfacing of the Mar...,"['Banks, Maria E.', 'Byrne, Shane', 'Galla, Ka...",2010,2010JGRE..115.8006B,Journal of Geophysical Research (Planets)
140972,6765,Zunil,"Crater, craters",AA,['Hadriaca Patera: Insights into its volcanic ...,"['Williams, David A.', 'Greeley, Ronald', 'Zus...",2007,2007JGRE..11210004W,Journal of Geophysical Research (Planets)
140973,6765,Zunil,"Crater, craters",AA,['Evidence for late Hesperian lacustrine activ...,"['Di Achille, Gaetano', 'Ori, Gian Gabriele', ...",2007,2007JGRE..112.7007D,Journal of Geophysical Research (Planets)
140974,6765,Zunil,"Crater, craters",AA,['Erosion rates at the Mars Exploration Rover ...,"['Golombek, M. P.', 'Grant, J. A.', 'Crumpler,...",2006,2006JGRE..11112S10G,Journal of Geophysical Research (Planets)
140975,6765,Zunil,"Crater, craters",AA,['Surficial properties of landslides and surro...,"['Chojnacki, Matthew', 'Jakosky, Bruce M.', 'H...",2006,2006JGRE..111.4005C,Journal of Geophysical Research (Planets)
140976,6765,Zunil,"Crater, craters",AA,['Subsurface volatile content of martian doubl...,"['Viola, Donna', 'McEwen, Alfred S.', 'Dundas,...",2017,2017Icar..284..325V,Icarus
140977,6765,Zunil,"Crater, craters",AA,['Sedimentological analyses of martian gullies...,"['de Haas, Tjalling', 'Ventra, Dario', 'Hauber...",2015,2015Icar..258...92D,Icarus
140978,6765,Zunil,"Crater, craters",AA,['Predicted detection rates of regional-scale ...,"['Teanby, N. A.']",2015,2015Icar..256...49T,Icarus
140979,6765,Zunil,"Crater, craters",AA,['The geology and mineralogy of Ritchey crater...,"['Sun, Vivian Z.', 'Milliken, Ralph E.']",2014,2014JGRE..119..810S,Journal of Geophysical Research (Planets)
140980,6765,Zunil,"Crater, craters",AA,['Quantitative morphology of rocks at the Mars...,"['Yingst, R. Aileen', 'Haldemann, A. F. C.', '...",2007,2007JGRE..112.6002Y,Journal of Geophysical Research (Planets)
140981,6765,Zunil,"Crater, craters",AA,['Tectonic pressurization of aquifers in the f...,"['Hanna, Jeffrey C.', 'Phillips, Roger J.']",2006,2006JGRE..111.3003H,Journal of Geophysical Research (Planets)
140982,6765,Zunil,"Crater, craters",AA,['Crater gradation in Gusev crater and Meridia...,"['Grant, J. A.', 'Arvidson, R. E.', 'Crumpler,...",2006,2006JGRE..111.2S08G,Journal of Geophysical Research (Planets)
140983,6765,Zunil,"Crater, craters",AA,['Modification history of the Harmakhis Vallis...,"['Kukkonen, S.', 'Kostama, V. -P.']",2018,2018Icar..299...46K,Icarus
140984,6765,Zunil,"Crater, craters",AA,['Hydrological and sedimentary analyses of wel...,"['Salese, Francesco', 'Di Achille, Gaetano', '...",2016,2016JGRE..121..194S,Journal of Geophysical Research (Planets)
140985,6765,Zunil,"Crater, craters",AA,['Inverted fluvial features in the Aeolis-Zeph...,"['Lefort, Alexandra', 'Burr, Devon M.', 'Beyer...",2012,2012JGRE..117.3007L,Journal of Geophysical Research (Planets)
140986,6765,Zunil,"Crater, craters",AA,['Constraints on ripple migration at Meridiani...,"['Golombek, M.', 'Robinson, K.', 'McEwen, A.',...",2010,2010JGRE..115.0F08G,Journal of Geophysical Research (Planets)
140987,6765,Zunil,"Crater, craters",AA,['Context Camera Investigation on board the Ma...,"['Malin, Michael C.', 'Bell, James F.', 'Canto...",2007,2007JGRE..112.5S04M,Journal of Geophysical Research (Planets)
140988,6765,Zunil,"Crater, craters",AA,['Geology of the Gusev cratered plains from th...,"['Golombek, M. P.', 'Crumpler, L. S.', 'Grant,...",2006,2006JGRE..111.2S07G,Journal of Geophysical Research (Planets)
140989,6765,Zunil,"Crater, craters",AA,['Quantifying geological processes on Mars-Res...,"['Jaumann, R.', 'Tirsch, D.', 'Hauber, E.', 'A...",2015,2015P&SS..112...53J,Planetary and Space Science
140990,6765,Zunil,"Crater, craters",AA,['Ancient and recent clay formation on Mars as...,"['Sun, Vivian Z.', 'Milliken, Ralph E.']",2015,2015JGRE..120.2293S,Journal of Geophysical Research (Planets)
140991,6765,Zunil,"Crater, craters",AA,['Columbus crater and other possible groundwat...,"['Wray, J. J.', 'Milliken, R. E.', 'Dundas, C....",2011,2011JGRE..116.1001W,Journal of Geophysical Research (Planets)
140992,6765,Zunil,"Crater, craters",AA,['Quantifying the amount of impact ejecta at t...,"['Cohen, Barbara A.']",2006,2006GeoRL..33.5203C,Geophysical Research Letters
140993,6768,Zutphen,"Crater, craters",AA,['La géologie des surfaces lunaire et planétai...,"['Masson, P.', 'Thomas, P.']",1984,1984LAstr..98..503M,L'Astronomie
140994,6768,Zutphen,"Crater, craters",AA,"['Wind-related features in Gusev crater, Mars']","['Greeley, Ronald', 'Kuzmin, Ruslan O.', 'Rafk...",2003,2003JGRE..108.8077G,Journal of Geophysical Research (Planets)
140995,6768,Zutphen,"Crater, craters",AA,"['Structure, stratigraphy, and origin of Husba...","['McCoy, T. J.', 'Sims, M.', 'Schmidt, M. E.',...",2008,2008JGRE..113.6S03M,Journal of Geophysical Research (Planets)
140996,6768,Zutphen,"Crater, craters",AA,['Quantifying the amount of impact ejecta at t...,"['Cohen, Barbara A.']",2006,2006GeoRL..33.5203C,Geophysical Research Letters

><h1> Visualization(Leaflet) </h1>
><h3> Completed </h3>
><h3><font color = "Grey">1. Mars Polygon Map</h3>
><h3><font color = "Grey">2. Heatmap with Bibliographic stats</h3>
><h3><font color = "Grey">3. Feature Type Filter + Landing Sites </h3>
><h3><font color = "Grey">4. Search Feature Name + Zoom in to the feature </h3>
><h3><font color = "Grey">5. Mouse over Info : Feature Name & Information </h3>

> [Link to the map](https://shinjjo.github.io/map.html)
---------------------------------------------------------------------------------------------------------------------------------------------------------------

><h1> Visualization(Leaflet) </h1>

><h3> To be Completed </h3>
<h3><font color = "Grey">6. Publication Information </h3>
<h3><font color = "Grey">+Moon Data </h3>

><h2>Problems</h2>
<h3><font color="Grey">1. Incomplete and incorrect Polygon Data</h3>
<h3><font color="Grey">2. Too Many Poylgons Overlap</h3>
<h3><font color="Grey">3. Common Feature Names (South, Freedom, Can....)</h3>